language: go

env:
  global:
    - CC_TEST_REPORTER_ID=3792e2667b73b4d48c209971071266709a71502569d15b42341d82861c52c01f
    - CODECOV_TOKEN="c1800f0b-a091-4e8f-a9f1-f43a92eb6d8f"

go:
  - master

git:
  depth: 1

install: true

notifications:
  email: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - go get ./...

script:
  - go test -v -race -coverprofile c.out ./...  

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT