language: go

env:
  global:
    - CODECOV_TOKEN="c1800f0b-a091-4e8f-a9f1-f43a92eb6d8f"

go:
  - master

git:
  depth: 1

install: true

notifications:
  email: true

before_script:
  - go get ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash)